In [1]:
#Basic structure of a function
def fun():
  print("Hello World!")

fun()

Hello World!

In [2]:
#Parameterized function
def fun2(x): # 'x' is parameter
  while x>0:
    x=x-1
    print("Hello World!")

fun2(3) # '3' is argument

Hello World!
Hello World!
Hello World!

In [3]:
#Default Parameter
def fun3(x="Python"):
  print(f"I am {x}.")

fun3()
fun3("Java")

I am Python.
I am Java.

In [4]:
#Return value
def fun4(x,y):
  sum=x+y
  return sum

ans = fun4(54,58)
print(ans+5)

117

In [5]:
#Doc
def fun5(x):
  """
  This function prints the square of a number.
  """
  print(x*x)

fun5(5)

help(fun5) # ami j description ta likhsi seta dekhabe

25
Help on function fun5 in module __main__:

fun5(x)
    This function prints the square of a number.

In [6]:
#Buid-in function gular khatrew use kora jai
help(print)

Help on built-in function print in module builtins:

print(*args, sep=' ', end='\n', file=None, flush=False)
    Prints the values to a stream, or to sys.stdout by default.

    sep
      string inserted between values, default a space.
    end
      string appended after the last value, default a newline.
    file
      a file-like object (stream); defaults to the current sys.stdout.
    flush
      whether to forcibly flush the stream.

In [7]:
#Positional arguments
def fun6(*args):
  print(args)

fun6(10,40,30,20) #serially tuple hisabe chole jabe

(10, 40, 30, 20)

In [8]:
#Keyword arguments
def fun7(a,b,c):
  print(a,b,c)

fun7(c=90,a=30,b=60)

30 60 90

In [9]:
#Variable Side Keyword arguments
def fun6(**kwargs):
  print(kwargs)

fun6(a=10,c=40,b=30,d=20) #serially dictionary hisabe chole jabe

{'a': 10, 'c': 40, 'b': 30, 'd': 20}

In [10]:
#Return more than one value
def fun8(a,b,c):
  a=a*2
  b=b*2
  c=c*2
  return a,b,c

x,y,z = fun8(5,6,7)
m = fun8(2,3,4) # tuple hisabe asbe

print(x,y,z)
print(m)

10 12 14
(4, 6, 8)

In [11]:
#Return more than one value as list
def fun9(a,b,c):
  a=a*2
  b=b*2
  c=c*2
  return [a,b,c]

m = fun9(2,3,4) # list hisabe asbe
print(m)

[4, 6, 8]

In [14]:
#iterator
a={10,20,30}
it=iter(a)

print(next(it))
print(next(it))
print(next(it))

10
20
30

In [18]:
#generator
variable_a=[x for x in range(500)]

def fun10(x, variable_a):
  for i in range(len(variable_a)):
    yield variable_a[i:i+x]

variable_b=fun10(10, variable_a)
print(variable_b)
print(type(variable_b))

<generator object fun10 at 0x7b912f720ba0>
<class 'generator'>

In [28]:
#lambda and apply function
import pandas as pd
df=pd.DataFrame({'Roll_Number': [5,10,15,20] })
print(df)

df['Roll_Square']=df['Roll_Number'].apply(lambda x : x*x) #dataset e new col create kora hoyese
print(df)
print()
df

   Roll_Number
0            5
1           10
2           15
3           20
   Roll_Number  Roll_Square
0            5           25
1           10          100
2           15          225
3           20          400

   Roll_Number  Roll_Square
0            5           25
1           10          100
2           15          225
3           20          400

In [31]:
#lambda and map function
import pandas as pd
df2=pd.DataFrame({'Roll_Number': [5,10,15,20] })
print(df2)

df2['Roll_Square']=df2['Roll_Number'].map(lambda x : x*x) #dataset e new col create kora hoyese
print(df2)
print()
df2

   Roll_Number
0            5
1           10
2           15
3           20
   Roll_Number  Roll_Square
0            5           25
1           10          100
2           15          225
3           20          400

   Roll_Number  Roll_Square
0            5           25
1           10          100
2           15          225
3           20          400

In [35]:
#lambda and map function
import pandas as pd
df3=pd.DataFrame({'Roll_Number': [5,10,15,20] })
print(df3)

df3['Roll_grater_than_10']=df3['Roll_Number'].map(lambda x : 1 if x>10 else 0) #dataset e new col create kora hoyese
print(df3)
print()
df3

   Roll_Number
0            5
1           10
2           15
3           20
   Roll_Number  Roll_grater_than_10
0            5                    0
1           10                    0
2           15                    1
3           20                    1

   Roll_Number  Roll_grater_than_10
0            5                    0
1           10                    0
2           15                    1
3           20                    1